### ISSUE TITLE
Update to use `/api/v2/transactions` to get transactions for addresses

### ISSUE THREAD

**Issue by iketheadore** [SkycoinProject/skycoin-explorer#6]
The API `/api/v2/transactions` with pagination has been deployed,  now we need to change the explorer to use this API to acquire transactions for addresses.

**Comment by iketheadore** [comment]
@Senyoret1 can you help to update the explorer to use the `/api/v2/transactions` to load transactions of addresses with pagination.

**Comment by Senyoret1** [comment]
Sorry for not paying much attention to this before. Maybe it will take a bit to be solved, as other things need more atention right now, but I just checked how to implement it and found this:

Using the new endpoint for getting the transaction history of all addresses may not be the best idea, as that would requiere to remove from the explorer some fields, like the one which says how many coins have entered and left the address, and the one for knowing the final balance of the address after each transaction. The reason for this is that the API does not return those values and the client code calculates them by checking all transactions. However, the endpoint is needed for some addresses which have a ton of transactions.

My idea is this: we can use the new paginated enpoint to get the transactions and also to know if the address has a lot of transactions. If the total number is low (lets say 100), then get all the transactions, to be able to calculate the values I mentioned before. However, if the address has many transactions, use the paginated endpoint and remove from the UI the fields which can not be calculated. It is not super elegant, but may be a way to get the best of both words.

If you think it is ok, I can make it work that way after finishing some other tasks.

**Comment by iketheadore** [comment]
We could do it as you suggested first. We may need a middleware service that provides API for explorer to get the total inputs coins and output coins later.  All things will be cached so that we don't have to get all transactions to calculate those values every time.
